In [5]:
import numpy as np
arr1 = np.array([9, 4, 16])
arr2= np.sqrt(arr1)
arr3 = arr2.astype(int)
print(arr3)


[3 2 4]


# axis=1 in column  and the axis=0 rows 

In [10]:
arr1 = np.array([[9, 4, 16],[25,49,64]])
arr2= np.sqrt(arr1)
arr3 = np.concatenate((arr1, arr2),axis=0).astype(int)
print(arr3)

[[ 9  4 16]
 [25 49 64]
 [ 3  2  4]
 [ 5  7  8]]


In [12]:
arr1 = np.array([[9, 4, 16],[25,49,64]])
arr2= np.sqrt(arr1)
print(np.vstack((arr1, arr2)).astype(int))

[[ 9  4 16]
 [25 49 64]
 [ 3  2  4]
 [ 5  7  8]]


In [11]:
arr1 = np.array([[9, 4, 16],[25,49,64]])
arr2= np.sqrt(arr1)
arr3 = np.concatenate((arr1, arr2),axis=1).astype(int)
print(arr3)

[[ 9  4 16  3  2  4]
 [25 49 64  5  7  8]]


In [13]:
arr1 = np.array([[9, 4, 16],[25,49,64]])
arr2= np.sqrt(arr1)
print(np.hstack((arr1, arr2)).astype(int))

[[ 9  4 16  3  2  4]
 [25 49 64  5  7  8]]


In [14]:
a= np.array([20,40,30,40,10,20])
b= np.array_split(a,3)
print(b[1])

[30 40]


In [27]:
import numpy
a= np.array([[20,40,30,40,10,20],[40,30,50,10,20,40]])
b= np.array([[40,30,60,10,20,40],[90,40,30,40,10,20]])
print(a,"\n",b)

c= np.cumprod([a,b], axis=1)

print(c)

print(c[1].sum())



[[20 40 30 40 10 20]
 [40 30 50 10 20 40]] 
 [[40 30 60 10 20 40]
 [90 40 30 40 10 20]]
[[[  20   40   30   40   10   20]
  [ 800 1200 1500  400  200  800]]

 [[  40   30   60   10   20   40]
  [3600 1200 1800  400  200  800]]]
8200


# corrcoef define the relation between the two data
# 0-means no relation ,-1 means inversely proportional, 1 means propostional relantion

In [28]:
tobacco = [30,40,50,10,20,60]
deaths= [100, 200, 300, 25, 50, 400]
print(np.corrcoef(tobacco, deaths))

[[1.        0.9797052]
 [0.9797052 1.       ]]


# to add the exel file in jupyter we need to install (pip install openpyxl
)

In [4]:
import pandas as pd
data = {"months": ["January", "February", "March", "April", "May", "June"]}
a = pd.DataFrame(data)
print(a)

# a["short_name"] = a["months"].str[:3]
a["short_name"] = a["months"].map(lambda x: x[:3])
print(a)

     months
0   January
1  February
2     March
3     April
4       May
5      June
     months short_name
0   January        Jan
1  February        Feb
2     March        Mar
3     April        Apr
4       May        May
5      June        Jun


# groupby 
# example
# gp = data.groupby("country").agg({"age":"mean"})
# it will make the group of the country with the mean of the age
# gp = data.groupby(["country", gender]).agg({"annual salary":"max","age":"count"})
# it will make the group of the country with the each gender and count the gender in that country

# to merge the data of the tabel
# pd.merge(df1, df2, on="emp id" , how ="left") on is use because on basis of we want to merge the table after that how will define the type of join means we want to write the common data or left most table data or right most table data

# if we want to concatenate the must be similar data on both the data or table we want to concatenate means no of column must be same

# comapre 
# df.compare(df1) it will compare both table and there is same no of column
# df.compare(df1, keep_shape=true) keep_shape will define the change two table and if no difference is there than it will write the NA in place of it and =false give the result table